#   Tia's Grindstone Enhanced plugin
#   Visit my site for more Tia's plugin
#   https://codeout.ttfl.net/minecraft

#   permissions:
#   tiagrindstone.command.open          open the grindstone menu
#   tiagrindstone.grindstone            use enhanced grindstone on grindstone
#   tiagrindstone.item.bypass           bypass item special list
#   tiagrindstone.enchantment.bypass    bypass enchantment blacklist/whitelist

grindstone:
  #   Should open enhanced menu when player right click grindstone?
  override-grindstone: true
  #   Should permission be required to open menu from grindstone?
  open-with-permission: false
  #   If player does not have permission. Use vanilla grindstone or
  #   block him from using grindstone?
  no-permission-use-vanilla: false
  #   Refer to i18n-message-open
  send-message-on-open: true
  #   Refer to i18n-message-remove
  send-message-on-remove: true

limits:
  items:
    #   Item types that are allowed to clean.
    #   To disable this, only keep something like Bedrock inside the list.
    global-list:
      - "leather_"
      - "wooden_"
      - "iron_"
      - "golden_"
      - "diamond_"
      - "netherite_"
      - "bow"
      - "crossbow"

    #   Item types that required permission to clean
    special-list:
      - "trident"

  books:
    #   Enable book clean?
    allow: true
    #   Require permission to clean books? Only useful when books are allowed above.
    use-permission: false

  #   Items/Books containing following keyword in their names will not be allowed.
  #   Could be useful if you have some custom items in your server (RPG)
  blacklist-names:
    - "Event Sword"
    - "Gift Chestplate"
    - "Book of EXP"

costs:
  #   Cost something on removing enchantments.
  #   none  : nothing
  #   give-coin     : give Vault coins. Required Vault!
  #   take-coin     : take Vault coins. Required Vault!
  #   give-exp      : give vanilla exp
  #   take-exp      : take vanilla exp
  #   give-exp-lvl  : give vanilla exp level
  #   take-exp-lvl  : take vanilla exp level

  #   Amount to cost when removing all enchantments from items/books.
  removing-all:
    type: give-exp
    #   Count all enchantments in the item for price?
    count-all: true
    #   Count all enchantments for price but max at a number.
    count-all-max: 100
    #   If count-all is false, set the amount here
    fix-amount: 50

  removing-single:
    type: take-coin
    #   Costs per level, eg, LVL5 enchantment take 5 x per-level = 50L
    per-level: 10
    #   These enchantments are on different price. eg, sharpness:11L
    override-price:
      - sharpness:11
      - protection:9

enchantment-list:
  #   false to use as whitelist, true to use as whitelist
  #   Players with permission can bypass whitelist/blacklist
  use-as-blacklist: true
  list:
    - curse_of_vanishing
    - curse_of_binding

i18n:
  message:
    open: "&e[Enhanced Grindstone] &aOpening the grindstone menu."
    permission-grindstone: "&e[Enhanced Grindstone] &cYou don't have the permission to use the grindstone."
    permission-open: "&e[Enhanced Grindstone] &cYou don't have the permission to use Enhanced Grindstone."
    remove: "&e[Enhanced Grindstone] &aSuccessfully remove %enchantment% from your item."
    not-allow: "&e[Enhanced Grindstone] &cThis item is not allowed in Grindstone."
    not-enough: "&e[Enhanced Grindstone] &cYou don't have enough %type% to do this!"
    item-dropped: "&e[Enhanced Grindstone] &aYou forgot your item! It's dropped at your location because your inventory is full!"
    reload: "&e[Enhanced Grindstone] &aConfig reloaded."
    reload-new: "&e[Enhanced Grindstone] &aConfig file not exists! Regenerating!"
  gui:
    title: "&eEnhanced Grindstone"
    lore:
      - ""
      - "&b%type% to remove this enchantment"
      - "&e | &b%price% %unit%"
    types:
      give-coin: "Money you get"
      take-coin: "Money you lose"
      give-exp: "EXP you get"
      take-exp: "EXP you lose"
      give-exp-lvl: "Lvl you get"
      take-exp-lvl: "Lvl you lose"
    unit:
      give-coin: " coin(s)"
      take-coin: " coin(s)"
      give-exp: " point(s)"
      take-exp: " point(s)"
      give-exp-lvl: " level(s)"
      take-exp-lvl: " level(s)"
    page:
      next: "Next Page (%current%/%total%)"
      previous: "Previous Page (%current%/%total%)"
  consoles:
    vault:
      not-found: "Vault is not installed. Some feature may be unavailable."
      no-provider: "Vault found. But no economy provider found. Some feature may be unavailable."
      hooked: "Vault hooked!"
    warning:
      negative-price: "Price cannot be negative number! Action cancelled!"
      invalid-type: "Invalid price type! Charge none!"
